services:
  hello-telemetry:
    build:
      context: ./app
    container_name: c008-hello-telemetry
    environment:
      OTEL_SERVICE_NAME: hello-telemetry
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_RESOURCE_ATTRIBUTES: deployment.environment=local-lab,course.id=c008
    ports:
      - "8000:8000"
    depends_on:
      otel-collector:
        condition: service_started

  python-zero-code:
    build:
      context: ./python_zero_code_app
    container_name: c008-python-zero-code
    environment:
      OTEL_SERVICE_NAME: python-zero-code
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_LOGS_EXPORTER: none
      OTEL_RESOURCE_ATTRIBUTES: deployment.environment=local-lab,course.id=c008,lab.section=instrumentation
    ports:
      - "8001:8001"
    depends_on:
      otel-collector:
        condition: service_started

  java-zero-code:
    build:
      context: ./java_zero_code_app
    container_name: c008-java-zero-code
    environment:
      OTEL_SERVICE_NAME: java-zero-code
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_LOGS_EXPORTER: none
      OTEL_RESOURCE_ATTRIBUTES: deployment.environment=local-lab,course.id=c008,lab.section=instrumentation
    ports:
      - "8080:8080"
    depends_on:
      otel-collector:
        condition: service_started

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.102.1
    container_name: c008-otel-collector
    command: ["--config=/etc/otelcol-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "8889:8889"
      - "13133:13133"
    depends_on:
      jaeger:
        condition: service_started

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: c008-jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: c008-prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=2h"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      otel-collector:
        condition: service_started

  grafana:
    image: grafana/grafana:11.1.0
    container_name: c008-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    depends_on:
      prometheus:
        condition: service_started
